### PR TITLE
My sql version provider

### PR DESCRIPTION
**Pull request by generik0**
Hi Antony
I have added the MsSqlVersionProvider.
I have also added a test for yhour reference.

Grab what you need :-)

BR Rik

### CODE REVIEW

**Comment by canton7** [comment]
Great, thanks! I'll probably next have a chance to look at this early next week.

**Comment by canton7** [comment]
Why did you close and delete this? I'm going to use your MySQL version provider.

**Comment by generik0** [comment]
Great.

 

I just redid my pull request. Sorry for the mess. I want happy with the commits.

 

Can you tell me hwhen yhou plan the MsSql and MySql release to Nuget?

I actually need it for a task :)

 

BR RIk

**Comment by canton7** [comment]
I'll release them properly on NuGet early to mid next week, probably.

You can get intermediate builds from this NuGet feed: https://ci.appveyor.com/nuget/simplemigrations. This has the latest commits, and contains your MSSQL work. You probably want version 0.9.3.61 - I removed the `ConnectionProvider` after that, and it will probably be reinstated.

**Comment by generik0** [comment]
Hi

If you do use the chance i made, then you could add another abstract class. The first level with TTransacrion and this has a base without a transaction.
That way you can handle both senatios :-)

Br Rik

**Comment by canton7** [comment]
I ended up going for an approach where the connection encapsulates the transaction: https://github.com/canton7/SimpleMigrations/commit/1f82d5724dcf2b45c6ba188f0454993324371dac. Look OK?

**Comment by generik0** [comment]
Looks good. A good solution.

 

BR Rik

**Comment by canton7** [comment]
v0.9.6 has been released on nuget.

**Pull request closed without merging**
