### PR TITLE
Ms sql version provider

### PR DESCRIPTION
**Pull request by generik0**
Hi
I have added a MsSqlVersionProvider and a test project.
Please note. The "Transactions" must be false. Otherwise you need to extend the ConnectionProvider with IConnectionProvider<IDbConnection,IDBTransaction> (i.e. add <TTransaction>). And return the transaction on the begintransaction in SimpleMigrator (And where ever else the generic is needed)

You see the command for the MsSql needs the transaction.. Up to you. Other DBs may have the same issue?

I can add it for you if you like?

By the way. Great little migrator. Saved me lots of trouble and bother. Didn't have to do FluentMigrator, nor Enity. Nice and thin.. Thanks.

I can add the MySql also if you like?

### CODE REVIEW

**Comment by canton7** [comment]
Thanks for this!

> Please note. The "Transactions" must be false. Otherwise you need to extend the ConnectionProvider with IConnectionProvider (i.e. add ). And return the transaction on the begintransaction in SimpleMigrator (And where ever else the generic is needed)

> You see the command for the MsSql needs the transaction.. Up to you. Other DBs may have the same issue?

I'm afraid I don't follow you. What "Transactions" are you referring to? What do you mean to add the IConnectionProvider to ConnectionProvider - ConnectionProvider already implements IConnectionProfider. I don't follow why BeginTransaction needs to return the transaction here either.

I don't see anything relating to transactions in your PR, and I'm not sure what issue you're referring to, I'm afraid.

I need to figure out a good approach to integration testing. I need to add a unit test project, but I don't think it's right to have integration tests in there: the CI server won't be able to run them, for a start.

A MySQL adapter would be fantastic 😃

**Comment by generik0** [comment]
Hi.

I added the test just to show you it works :-)

The mssql needs the transaction to be added the sql command. Otherwise it failed.

Your attribute on the Migrate allowed a false for use transaction. Otherwise the migration fails for MsSql.
Hence in the begintransaction call needs the transaction returned and sent to the command.
But as you have used generics for the database interface I did not want to hardcore the idbTransaction as a return from begintransaction.


Let me know what you think about this. We can have a skype meeting if you like?

Br Rik

**Comment by generik0** [comment]
Actually I had another question.
If I want to run the migration in a console application I created, is there a way to "pass" the existing console object/application to your console runner, so it is the same windows?
Or should I use your logger somehow to output to the main application window?

Br Rik

**Comment by canton7** [comment]
> The mssql needs the transaction to be added the sql command. Otherwise it failed.

Are you saying that your MSSQL version provider doesn't work, because it needs to run in a transaction?

> Your attribute on the Migrate allowed a false for use transaction. Otherwise the migration fails for MsSql.

Now you are saying that MSSQL migrations **fail** if they're run in a transaction? Hrm, maybe we need a way of specifying whether migrations are run in a transaction by default, or not.

I think you're saying that the MSSQL version provider needs to run in a transaction, but the MSSQL migrations cannot run in a transaction, which doesn't seem right.

> Hence in the begintransaction call needs the transaction returned and sent to the command.

I don't follow. Which command are you talking about. One of the ones in version provider?

> If I want to run the migration in a console application I created, is there a way to "pass" the existing console object/application to your console runner, so it is the same windows? Or should I use your logger somehow to output to the main application window?

So this is some custom console you've created, that doesn't use `Console.WriteLine`, etc? 

You won't be able to use the `ConsoleRunner`, as that assumes it's talking to a normal console. You can write a custom logger which will output the results of your migrations to your console though.

**Comment by generik0** [comment]
HI

 

Sorry about the confusement. This type of questions shouldn’t be done over a mobile. But need screenshots.

 

This works:



 



 

This fails:



 



 

 

 

If I add some temp code, it passes. You see I add the transaction to the command.:



 

 

What I am saying is, that for MsSQL the transaction needs to be a part of the command.

To do it properly and follow your design the  IConnectionProvider method for BeginTransaction should have return a transaction. But since the deign uses a generic for the database connection I guess the transaction should be a generic also



 

I will make a candidate and make a pull request :)

 

BR RIk

**Comment by canton7** [comment]
Unfortunately your images didn't come through, but I experimented with your MSSQL version provider and found them for myself.

I ended up changing how transactions are handled: it's now `Migration<T>` which puts the migration in a transaction, and I got rid of `IConnectionProvider`. This means we don't risk leaking `IDbConnection` across the codebase. See here: https://github.com/canton7/SimpleMigrations/commit/6e1fbb376d2bb34bcd1116784e12e399e61e8ee7.

I then extracted your version provider and test, and committed them (under your name) here: https://github.com/canton7/SimpleMigrations/commit/c8dc32dabc432e424e80c641cc7d2ba350d8a8e9.

Does that look sensible?

**Comment by generik0** [comment]
I will look.

But I just extended the classes and generics myself :)

The way you have done it is the most simple. 

 

I just pushed a pull request wher you can see I extended your generics..

I like your generics. Easy to add non IDBconnection and IDBtransaction support in the future (Although one shouldn’t program for the future:- )

 

BR Ri

**Comment by generik0** [comment]
Hi again

 

Your develop branch is using .Net Stanadard and you have a packages.json

Unfortunately the packages are not loading for me. You are not using nuget?

Can you tell me what to do?

**Comment by canton7** [comment]
>Unfortunately the packages are not loading for me.

What do you mean by that? What error are you getting? Make sure you have the .NET Core SDK Installed, [see here](https://www.microsoft.com/net/core#windows).

> You are not using nuget? Can you tell me what to do?

I'm still using nuget.

**Comment by generik0** [comment]
I havn’t upaded my VS to Update 3. Probably the issue. Sorry mate..

**Pull request closed without merging**
